variable "project" {
  description = "Project name, used in resource naming."
  type        = string
}

variable "environment" {
  description = "Environment name (dev/prod)."
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet IDs for the DB subnet group (at least 2, different AZs)."
  type        = list(string)
}

variable "security_group_id" {
  description = "Security group allowing ECS services in on 5432 (from modules/security)."
  type        = string
}

variable "engine_version" {
  description = "PostgreSQL major/minor version — matches the local postgres:16-alpine image's major version."
  type        = string
  default     = "16.4"
}

variable "instance_class" {
  description = "RDS instance class. db.t4g.medium is a reasonable dev default (burstable, Graviton); size up for prod via environments/prod's tfvars."
  type        = string
  default     = "db.t4g.medium"
}

variable "allocated_storage_gb" {
  description = "Initial storage, GB. gp3 autoscaling (max_allocated_storage_gb) handles growth beyond this."
  type        = number
  default     = 50
}

variable "max_allocated_storage_gb" {
  description = "Ceiling for RDS storage autoscaling — caps runaway growth/cost from a single misbehaving job rather than growing unbounded."
  type        = number
  default     = 200
}

variable "multi_az" {
  description = "Multi-AZ standby for automatic failover. false in dev (cost), should be true in prod."
  type        = bool
  default     = false
}

variable "backup_retention_days" {
  description = "Automated backup retention window, days."
  type        = number
  default     = 7
}

variable "deletion_protection" {
  description = "Prevents `terraform destroy`/console deletion without first disabling this flag — a deliberate speed bump against destroying the one stateful datastore every service depends on."
  type        = bool
  default     = true
}

variable "master_username" {
  description = "Master username for the RDS instance (not a per-service application user — see README for the documented per-service-database bootstrap step)."
  type        = string
  default     = "omniflow_admin"
}

variable "master_password" {
  description = "RDS master password, generated by modules/secrets (random_password) and passed in here — never a literal value in a tfvars file. Terraform, not AWS, owns this value so the environment root config can compose per-service DATABASE_URL secrets from it."
  type        = string
  sensitive   = true
}

variable "database_name" {
  description = "Name of the single database RDS creates at instance-creation time. The remaining per-service databases (omniflow_inventory, omniflow_orchestrator, omniflow_gateway, omniflow_failure_lab — see infra/docker/postgres/init-databases.sql) must be created afterward; see README's 'Post-provision manual step' — Terraform's AWS provider has no resource for creating additional databases inside an existing RDS instance without a live psql connection, which this task must not attempt."
  type        = string
  default     = "omniflow_orders"
}

variable "monitoring_interval_seconds" {
  description = "Enhanced Monitoring granularity, seconds. 0 disables it."
  type        = number
  default     = 60
}

variable "performance_insights_enabled" {
  description = "Enable Performance Insights (7-day free retention tier)."
  type        = bool
  default     = true
}

variable "tags" {
  description = "Common tags applied to every resource this module creates."
  type        = map(string)
  default     = {}
}
