# Every secret value here is generated by Terraform itself (the `random`
# provider) at apply time, never read from a variable/tfvars file — so
# there is no real secret value anywhere in version control, matching this
# repo's standing "no hardcoded secrets" rule. This module has never been
# applied (ADR 0007); these resources are authored and validated only.

locals {
  name_prefix = "${var.project}-${var.environment}"
}

resource "aws_kms_key" "secrets" {
  description         = "KMS key encrypting ${local.name_prefix} Secrets Manager secrets."
  enable_key_rotation = true

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-secrets-kms"
  })
}

resource "aws_kms_alias" "secrets" {
  name          = "alias/${local.name_prefix}-secrets"
  target_key_id = aws_kms_key.secrets.key_id
}

# --- RDS master password ----------------------------------------------------
# Generated here (not via RDS's own manage_master_user_password) so the
# environment root config can compose full postgresql+psycopg://... URL
# secrets per service database (matching each service's existing single-
# DATABASE_URL-env-var contract — see services/*/app/config.py) without
# needing application-code changes to assemble a URL from separate
# host/user/password parts, which is out of this phase's scope.
resource "random_password" "rds_master" {
  length = 32
  # RDS's own password character-set restriction: no "/", "@", '"', or space.
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "rds_master_password" {
  name                    = "${local.name_prefix}/rds/master-password"
  description             = "RDS PostgreSQL master password (Terraform-generated, never plaintext in version control)."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-rds-master-password"
  })
}

resource "aws_secretsmanager_secret_version" "rds_master_password" {
  secret_id     = aws_secretsmanager_secret.rds_master_password.id
  secret_string = random_password.rds_master.result
}

# --- JWT signing secret (ADR 0009) ------------------------------------------
# Symmetric (HS256) secret api-gateway signs with and failure-lab verifies
# with — same shared-secret requirement as the local docker-compose
# JWT_SECRET_KEY env var (DECISIONS.md "Phase 9").
resource "random_password" "jwt_secret" {
  length  = 64
  special = false # JWT_SECRET_KEY is consumed as a raw string env var; keep it shell/JSON-safe.
}

resource "aws_secretsmanager_secret" "jwt_secret_key" {
  name                    = "${local.name_prefix}/app/jwt-secret-key"
  description             = "Shared HS256 JWT signing secret (ADR 0009) — api-gateway issues, failure-lab verifies."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-jwt-secret-key"
  })
}

resource "aws_secretsmanager_secret_version" "jwt_secret_key" {
  secret_id     = aws_secretsmanager_secret.jwt_secret_key.id
  secret_string = random_password.jwt_secret.result
}

# --- Seeded demo-user passwords (ADR 0009) ----------------------------------
# api-gateway's app.seed idempotently creates admin/ops/viewer accounts plus
# the failure-lab service account at every startup, reading each password
# from its own env var (GATEWAY_SEED_*_PASSWORD) — same four accounts as
# .env.example, generated here instead of using the local dev-only defaults.
locals {
  seed_accounts = ["admin", "ops", "viewer", "service"]
}

resource "random_password" "seed_password" {
  for_each         = toset(local.seed_accounts)
  length           = 24
  special          = true
  override_special = "!#$%^&*()-_=+"
}

resource "aws_secretsmanager_secret" "seed_password" {
  for_each                = toset(local.seed_accounts)
  name                    = "${local.name_prefix}/app/gateway-seed-${each.value}-password"
  description             = "Seeded ${each.value} demo-account password for api-gateway's idempotent user seed (ADR 0009)."
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-gateway-seed-${each.value}-password"
  })
}

resource "aws_secretsmanager_secret_version" "seed_password" {
  for_each      = aws_secretsmanager_secret.seed_password
  secret_id     = each.value.id
  secret_string = random_password.seed_password[each.key].result
}
